#!/usr/bin/env bash
########################################
#  Simple go back script
########################################
#
#  Author: Facundo Montero <facumo.fm@gmail.com>
#
########################################
if [ -z $PREVPWD ]
then
 printf "You haven't used 'goto' yet, please try again after the first run.\n"
else
 printf "Back to '$PREVPWD'.\n"
 CURPWD=$PREVPWD
 PREVPWD=$(pwd)
 cd $CURPWD
fi
